os: linux
dist: xenial
language: node_js
env:
  global:
    - LAST_PUBLISHED_VERSION=$(npm run --silent version:latest-published)
    - BUILD_VERSION=$(npm run --silent version:current)
install:
  - npm install
  - npm run build
script:
  - 'echo last_published_version: $LAST_PUBLISHED_VERSION'
  - 'echo build version: $BUILD_VERSION'
  - npm run lint || travis_terminate 1
  - npm run test || travis_terminate 1
  - codecov
deploy:
  provider: npm
  email: joshuatvernon@gmail.com
  skip_cleanup: true
  on:
    branch: main
    condition: '$BUILD_VERSION != $LAST_PUBLISHED_VERSION'
  api_key: 85dfa01b-9262-4973-aaa5-0babe7311738
